version: '3.9'
services:
  notebook:
    build: 
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    ports:
      - "8888:8888"
    tty: true
    entrypoint: >
      jupyter lab 
      --port=8888 
      --ip=0.0.0.0 
      --allow-root 
      --NotebookApp.token=''
      --notebook-dir=/workspace